/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.mariadb.jdbc.Connection;
import repository.TodoRepo;
import util.DBUtil;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
///
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;


// author Team Simpin :Christian Hutahaean,Elkana Sitorus,Lola Tampubolon,Marshall Manurung,Ruth Manurung
public class Anggota extends javax.swing.JFrame {
    
    private boolean isEnglish = false; 
    private int jumlahAnggota;
    public Anggota() {
        initComponents();
        loadMemberData();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        roundedpanel2 = new aplikasi.simpin.component.roundedpanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelCover1 = new aplikasi.simpin.component.PanelCover();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        roundedpanel3 = new aplikasi.simpin.component.roundedpanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jLabel10.setBackground(new java.awt.Color(0, 149, 117));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SIMPANAN");

        roundedpanel2.setRoundBottomLeft(15);
        roundedpanel2.setRoundBottomright(15);
        roundedpanel2.setRoundTopLeft(15);
        roundedpanel2.setRoundTopRight(15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID Anggota");

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Simpanan");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simpanan Pokok", "Simpanan Wajib", "Simpanan Sukarela" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jenis Simpanan");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("-");

        jButton2.setBackground(new java.awt.Color(0, 121, 107));
        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedpanel2Layout = new javax.swing.GroupLayout(roundedpanel2);
        roundedpanel2.setLayout(roundedpanel2Layout);
        roundedpanel2Layout.setHorizontalGroup(
            roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundedpanel2Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedpanel2Layout.setVerticalGroup(
            roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCover1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/simpin/assets/1-removebg-preview (1).png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 149, 117));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        roundedpanel3.setRoundBottomLeft(15);
        roundedpanel3.setRoundBottomright(15);
        roundedpanel3.setRoundTopLeft(15);
        roundedpanel3.setRoundTopRight(15);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Nama ");

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Jenis Kelamin");

        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("No hp");

        jComboBox2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Male", "Female" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 121, 107));
        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Daftar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Nik");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Alamat");

        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout roundedpanel3Layout = new javax.swing.GroupLayout(roundedpanel3);
        roundedpanel3.setLayout(roundedpanel3Layout);
        roundedpanel3Layout.setHorizontalGroup(
            roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel3Layout.createSequentialGroup()
                .addGroup(roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedpanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(roundedpanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedpanel3Layout.setVerticalGroup(
            roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Jenis Kelamin", "Nik", "No hp", "Alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setBackground(new java.awt.Color(0, 149, 117));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Daftar Anggota");

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Berdasarkan NIK:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Berdasarkan NIK:");

        jButton6.setBackground(new java.awt.Color(0, 121, 107));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 121, 107));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 121, 107));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 121, 107));
        jButton9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton4.setText("Ganti Bahasa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton5.setText("Log Activity");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton10.setText("Download Laporan");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCover1Layout = new javax.swing.GroupLayout(panelCover1);
        panelCover1.setLayout(panelCover1Layout);
        panelCover1Layout.setHorizontalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(305, 305, 305))
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCover1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(roundedpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)))
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCover1Layout.createSequentialGroup()
                                    .addGap(254, 254, 254)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(300, 300, 300))
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
            .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCover1Layout.createSequentialGroup()
                    .addGap(528, 528, 528)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(528, Short.MAX_VALUE)))
        );
        panelCover1Layout.setVerticalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                            .addComponent(roundedpanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
            .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCover1Layout.createSequentialGroup()
                    .addGap(303, 303, 303)
                    .addComponent(jLabel2)
                    .addContainerGap(304, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCover1, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCover1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
        
 /// method cloud data anggota     
 public void loadMemberData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // Create a left-alignment renderer
    DefaultTableCellRenderer leftAlignRenderer = new DefaultTableCellRenderer();
    leftAlignRenderer.setHorizontalAlignment(SwingConstants.LEFT);
    
    // Apply left alignment to all columns
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(leftAlignRenderer);
    }

    // Reset the table data to avoid duplicate entries
    model.setRowCount(0);

    // Load data from database
    TodoRepo repo = new TodoRepo();
    repo.loadMembersFromDatabase(model);  // Assuming this method loads all members from DB into the table
}
    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String nama = jTextField3.getText();
String jenisKelamin = jComboBox2.getSelectedItem().toString();
String nik = jTextField7.getText();
String noHp = jTextField11.getText();
String alamat = jTextField12.getText();

// Cek apakah jenis kelamin sudah dipilih
if (jenisKelamin.equalsIgnoreCase("Pilih")) {
    JOptionPane.showMessageDialog(this, "Jenis Kelamin belum dipilih", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Cek apakah semua field telah diisi
if (nama.isEmpty() || nik.isEmpty() || noHp.isEmpty() || alamat.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Cek apakah nomor HP (noHp) hanya berisi angka dan memiliki panjang antara 10 hingga 13 digit
if (!noHp.matches("\\d{10,13}")) {
    JOptionPane.showMessageDialog(this, "Nomor HP harus terdiri dari 10 hingga 13 digit angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Cek apakah alamat (jTextField12) hanya terdiri dari huruf dan angka (kombinasi string dan integer diperbolehkan)
if (!alamat.matches("[a-zA-Z0-9\\s]+")) {
    JOptionPane.showMessageDialog(this, "Alamat hanya boleh berisi huruf, angka, dan spasi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

TodoRepo repo = new TodoRepo();
int result = repo.addMemberToDatabase(nama, jenisKelamin, nik, noHp, alamat);

if (result <= 0) {
    JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database!", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Tambahkan data ke dalam model tabel
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int nomorUrut = model.getRowCount() + 1;
model.addRow(new Object[]{nomorUrut, nama, jenisKelamin, nik, noHp, alamat});

jumlahAnggota = model.getRowCount();  // Update jumlahAnggota after adding

// Set renderer untuk semua kolom agar data rata kiri
DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
leftRenderer.setHorizontalAlignment(SwingConstants.LEFT);

for (int i = 0; i < jTable1.getColumnCount(); i++) {
    jTable1.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
}

JOptionPane.showMessageDialog(this, "Anggota berhasil didaftarkan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

// Reset input
jTextField3.setText("");
jTextField7.setText("");
jTextField11.setText("");
jTextField12.setText("");
jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);  // Tampilkan JFrame Dashboard
            this.dispose();              // Menutup JFrame Anggota
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error membuka Dashboard: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      String idAnggotaInput = jTextField8.getText().trim();

// Cek apakah input kosong
if (idAnggotaInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan ID anggota yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}
// Dapatkan model asli dari JTable
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
// Buat TableRowSorter untuk menyaring data di JTable
TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
jTable1.setRowSorter(sorter);
// Filter berdasarkan ID Anggota (kolom ke-4, indeks ke-3)
RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter("^" + idAnggotaInput + "$", 3); // 3 adalah indeks kolom ke-4
sorter.setRowFilter(rf);
// Cek apakah ada hasil yang ditampilkan setelah filter
if (sorter.getViewRowCount() == 0) {
    JOptionPane.showMessageDialog(this, "ID anggota tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
    // Reset filter agar menampilkan semua data kembali
    sorter.setRowFilter(null);
}

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           String nikInput = jTextField8.getText().trim();
    if (nikInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan NIK yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data dengan NIK: " + nikInput + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        TodoRepo repo = new TodoRepo();
        int result = repo.deleteMemberFromDatabase(nikInput);

        if (result > 0) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            boolean found = false;

            for (int i = 0; i < model.getRowCount(); i++) {
                String tableNik = model.getValueAt(i, 3).toString().trim();
                if (tableNik.equals(nikInput)) {
                    model.removeRow(i);
                    found = true;
                    break;
                }
            }
            if (found) {
                jumlahAnggota = model.getRowCount();  // Update jumlahAnggota after deletion  
                JOptionPane.showMessageDialog(this, "Anggota telah dihapus dari data", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Anggota tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "NIK tidak ditemukan di database.", "Error", JOptionPane.ERROR_MESSAGE);
        }}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      String nikInput = jTextField8.getText().trim(); // Ambil input dari JTextField8
     // Cek apakah input kosong
     if (nikInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan NIK yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Dapatkan model asli dari JTable
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// Buat TableRowSorter untuk menyaring data di JTable
TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
jTable1.setRowSorter(sorter);

// Filter berdasarkan NIK (kolom ke-4, indeks ke-3)
RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter("^" + nikInput + "$", 3); // Indeks 3 untuk kolom ke-4 (NIK)
sorter.setRowFilter(rf);

// Cek apakah ada hasil yang ditampilkan setelah filter
if (sorter.getViewRowCount() == 0) {
    JOptionPane.showMessageDialog(this, "NIK tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
    // Reset filter agar menampilkan semua data kembali
    sorter.setRowFilter(null);
    return;
}

// Jika ditemukan, ambil indeks baris yang sesuai dengan filter
int modelRowIndex = sorter.convertRowIndexToModel(0); // Ambil baris pertama yang cocok

// Ambil data dari baris yang cocok
String nama = model.getValueAt(modelRowIndex, 1).toString(); // Kolom Nama
String jenisKelamin = model.getValueAt(modelRowIndex, 2).toString(); // Kolom Jenis Kelamin
String noHp = model.getValueAt(modelRowIndex, 4).toString(); // Kolom No HP
String alamat = model.getValueAt(modelRowIndex, 5).toString(); // Kolom Alamat

// Tampilkan dialog untuk mengedit data
String newNama = JOptionPane.showInputDialog(this, "Edit Nama:", nama);

// Gunakan JComboBox untuk pilihan jenis kelamin
JComboBox<String> genderComboBox = new JComboBox<>(new String[]{"Male", "Female"});
genderComboBox.setSelectedItem(jenisKelamin); // Set nilai awal sesuai data lama

int genderOption = JOptionPane.showConfirmDialog(
    this,
    genderComboBox,
    "Edit Jenis Kelamin:",
    JOptionPane.OK_CANCEL_OPTION,
    JOptionPane.PLAIN_MESSAGE
);

// Ambil nilai yang dipilih dari JComboBox jika pengguna menekan OK
String newJenisKelamin = (genderOption == JOptionPane.OK_OPTION) ? (String) genderComboBox.getSelectedItem() : null;

String newNoHp = JOptionPane.showInputDialog(this, "Edit No HP:", noHp);
String newAlamat = JOptionPane.showInputDialog(this, "Edit Alamat:", alamat);

// Update data di JTable jika pengguna tidak membatalkan input
if (newNama != null && newJenisKelamin != null && !newJenisKelamin.equals("Pilih") && newNoHp != null && newAlamat != null) {
    model.setValueAt(newNama, modelRowIndex, 1);           // Update kolom Nama
    model.setValueAt(newJenisKelamin, modelRowIndex, 2);   // Update kolom Jenis Kelamin
    model.setValueAt(newNoHp, modelRowIndex, 4);           // Update kolom No HP
    model.setValueAt(newAlamat, modelRowIndex, 5);         // Update kolom Alamat

    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Info", JOptionPane.INFORMATION_MESSAGE);
} else {
    JOptionPane.showMessageDialog(this, "Edit dibatalkan atau jenis kelamin tidak valid.", "Peringatan", JOptionPane.WARNING_MESSAGE);
}

// Reset filter untuk menampilkan semua data kembali
sorter.setRowFilter(null);


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (jTable1.getRowSorter() != null) {
            // Reset filter agar semua data tampil kembali
            ((TableRowSorter<?>) jTable1.getRowSorter()).setRowFilter(null);
        } else {
            // Jika tidak menggunakan TableRowSorter, bisa langsung refresh model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.fireTableDataChanged(); // Memastikan data tabel diperbarui
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      if (isEnglish) {
        // Set text labels for Indonesian
        jLabel11.setText("Daftar Anggota");
        jLabel13.setText("Nama");
        jLabel14.setText("Jenis Kelamin");
        jLabel19.setText("Nik");
        jLabel15.setText("No Hp");
        jLabel20.setText("Alamat");
        jLabel16.setText("Berdasarkan NIK");
        jButton6.setText("Cari");
        jButton7.setText("Hapus");
        jButton8.setText("Ubah");
        jButton9.setText("Ulang");
        jButton4.setText("Ganti bahasa");
         jButton3.setText("Reset");
         jButton5.setText("Log aktivitas");

        // Set table column headers for Indonesian
        jTable1.getColumnModel().getColumn(0).setHeaderValue("No");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Nama");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Jenis Kelamin");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Nik");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("No Hp");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Alamat");

    } else {
        // Set text labels for English
        jLabel11.setText("Member List");
        jLabel13.setText("Name");
        jLabel14.setText("Gender");
        jLabel19.setText("Nik");
        jLabel15.setText("No Hp");
        jLabel20.setText("Address");
        jLabel16.setText("Based on NIK");
        jButton6.setText("Search");
        jButton7.setText("Delete");
        jButton8.setText("Edit");
        jButton9.setText("Reset");
        jButton3.setText("Register");
        jButton4.setText("Change language");
         jButton5.setText("Log activity");

        // Set table column headers for English
        jTable1.getColumnModel().getColumn(0).setHeaderValue("No");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Name");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Gender");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Nik");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("No Hp");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Address");
    }

    // Refresh the table header after changing the language
    jTable1.getTableHeader().repaint();

    // Toggle the language flag for next usage
    isEnglish = !isEnglish;


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     String sql = "SELECT nama, created_at FROM members ORDER BY created_at ASC";  // Query SQL untuk mengambil semua anggota

try (Connection connection = (Connection) DBUtil.getConnection();
     PreparedStatement stmt = connection.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder messageBuilder = new StringBuilder("Daftar Anggota Terdaftar:\n\n");
    int totalAnggota = 0;  // Variabel untuk menghitung jumlah anggota

    // Mengolah hasil query
    while (rs.next()) {
        String nama = rs.getString("nama");  // Mengambil nama anggota
        java.sql.Timestamp timestamp = rs.getTimestamp("created_at");  // Mengambil waktu pendaftaran

        // Konversi timestamp ke LocalDateTime
        java.time.LocalDateTime waktu = timestamp.toLocalDateTime();

        // Format waktu ke HH:mm:ss
        String waktuFormatted = waktu.format(java.time.format.DateTimeFormatter.ofPattern("HH:mm:ss"));

        // Mengambil nama hari dalam bahasa Indonesia
        String namaHari = waktu.format(java.time.format.DateTimeFormatter.ofPattern("EEEE", new java.util.Locale("id", "ID")));

        // Menambahkan nama anggota dan waktu ke dalam message
        messageBuilder.append("Nama: ").append(nama).append("\n")
                      .append("Terdaftar pada: ").append(waktuFormatted).append(" (").append(namaHari).append(")\n\n");

        totalAnggota++;  // Menambah jumlah anggota yang terdaftar
    }

    // Jika tidak ada anggota yang terdaftar
    if (totalAnggota == 0) {
        JOptionPane.showMessageDialog(null, "Tidak ada anggota yang terdaftar.", "Info", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Menambahkan informasi jumlah anggota
        messageBuilder.append("Jumlah Anggota Terdaftar: ").append(totalAnggota).append("\n");

        // Menampilkan pesan dalam bentuk card message
        JOptionPane.showMessageDialog(null, messageBuilder.toString(), "Informasi Anggota Terdaftar", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
     String outputFile = "D:\\Data_Anggota.pdf"; // Change this to save in C: drive

// Query untuk mengambil data anggota
String sql = "SELECT * FROM members";

try (Connection connection = (Connection) DBUtil.getConnection();
     PreparedStatement stmt = connection.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery()) {

    // Membuat dokumen PDF
    Document document = new Document();
    PdfWriter.getInstance(document, new FileOutputStream(outputFile));

    // Membuka dokumen untuk menulis
    document.open();

    // Menulis judul dokumen dengan bold
    Font boldFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
    document.add(new Paragraph("Daftar Anggota Terdaftar", boldFont));
    document.add(new Paragraph("========================================"));

    // Menulis data anggota
    while (rs.next()) {
        String nama = rs.getString("nama");
        String jenisKelamin = rs.getString("jenis_kelamin");
        String nik = rs.getString("nik");
        String noHp = rs.getString("no_hp");
        String alamat = rs.getString("alamat");
        String createdAt = rs.getString("created_at");

        // Menambahkan data anggota ke dalam dokumen PDF
        document.add(new Paragraph("Nama: " + nama));
        document.add(new Paragraph("Jenis Kelamin: " + jenisKelamin));
        document.add(new Paragraph("NIK: " + nik));
        document.add(new Paragraph("No HP: " + noHp));
        document.add(new Paragraph("Alamat: " + alamat));
        document.add(new Paragraph("Terdaftar pada: " + createdAt));
        document.add(new Paragraph("\n----------------------------------------\n"));
    }

    // Menutup dokumen PDF
    document.close();

    // Memberikan informasi kepada pengguna bahwa PDF telah dibuat
    JOptionPane.showMessageDialog(null, "Data anggota berhasil diekspor ke PDF: " + outputFile,
                                  "Berhasil", JOptionPane.INFORMATION_MESSAGE);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
} catch (FileNotFoundException e) {
    JOptionPane.showMessageDialog(null, "File tidak ditemukan atau tidak dapat disimpan.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
} catch (DocumentException ex) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat membuat file PDF.", "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}

    
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private aplikasi.simpin.component.PanelCover panelCover1;
    private aplikasi.simpin.component.roundedpanel roundedpanel2;
    private aplikasi.simpin.component.roundedpanel roundedpanel3;
    // End of variables declaration//GEN-END:variables
}
