/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import repository.TodoRepo;
import java.sql.SQLException;
import org.mariadb.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JComboBox;
import util.DBUtil;

// author Team Simpin :Christian Hutahaean,Elkana Sitorus,Lola Tampubolon,Marshall Manurung,Ruth Manurung

public class Pinjaman extends javax.swing.JFrame {

     private boolean isEnglish = false;
    public Pinjaman() {
        initComponents();
        loadMemberData();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedpanel1 = new aplikasi.simpin.component.roundedpanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        roundedpanel4 = new aplikasi.simpin.component.roundedpanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        roundedpanel3 = new aplikasi.simpin.component.roundedpanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        roundedpanel2 = new aplikasi.simpin.component.roundedpanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        panelCover1 = new aplikasi.simpin.component.PanelCover();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        roundedpanel5 = new aplikasi.simpin.component.roundedpanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        javax.swing.GroupLayout roundedpanel1Layout = new javax.swing.GroupLayout(roundedpanel1);
        roundedpanel1.setLayout(roundedpanel1Layout);
        roundedpanel1Layout.setHorizontalGroup(
            roundedpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
        roundedpanel1Layout.setVerticalGroup(
            roundedpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("-");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("-");

        roundedpanel4.setBackground(new java.awt.Color(204, 204, 204));
        roundedpanel4.setRoundBottomLeft(25);
        roundedpanel4.setRoundBottomright(25);
        roundedpanel4.setRoundTopLeft(25);
        roundedpanel4.setRoundTopRight(25);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total Anggota");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel7");

        javax.swing.GroupLayout roundedpanel4Layout = new javax.swing.GroupLayout(roundedpanel4);
        roundedpanel4.setLayout(roundedpanel4Layout);
        roundedpanel4Layout.setHorizontalGroup(
            roundedpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(roundedpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedpanel4Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        roundedpanel4Layout.setVerticalGroup(
            roundedpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(roundedpanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedpanel4Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        roundedpanel3.setBackground(new java.awt.Color(204, 204, 204));
        roundedpanel3.setRoundBottomLeft(25);
        roundedpanel3.setRoundBottomright(25);
        roundedpanel3.setRoundTopLeft(25);
        roundedpanel3.setRoundTopRight(25);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Anggota");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("jLabel7");

        javax.swing.GroupLayout roundedpanel3Layout = new javax.swing.GroupLayout(roundedpanel3);
        roundedpanel3.setLayout(roundedpanel3Layout);
        roundedpanel3Layout.setHorizontalGroup(
            roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedpanel3Layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
        roundedpanel3Layout.setVerticalGroup(
            roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(roundedpanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(roundedpanel3Layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        roundedpanel2.setRoundBottomLeft(15);
        roundedpanel2.setRoundBottomright(15);
        roundedpanel2.setRoundTopLeft(15);
        roundedpanel2.setRoundTopRight(15);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID Anggota");

        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Anggota");

        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Pinjaman");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjaman Konsumtif", "Pinjaman Produktif" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("No. Rekening");

        jButton2.setBackground(new java.awt.Color(0, 121, 107));
        jButton2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Durasi Pinjaman");

        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout roundedpanel2Layout = new javax.swing.GroupLayout(roundedpanel2);
        roundedpanel2.setLayout(roundedpanel2Layout);
        roundedpanel2Layout.setHorizontalGroup(
            roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        roundedpanel2Layout.setVerticalGroup(
            roundedpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCover1.setPreferredSize(new java.awt.Dimension(1047, 551));

        jButton6.setBackground(new java.awt.Color(0, 121, 107));
        jButton6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 121, 107));
        jButton7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 121, 107));
        jButton8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Nama", "Jenis Simpanan", "Jumlah", "No Rek", "Tanggal", "Bulan", "Tahun"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton9.setBackground(new java.awt.Color(0, 121, 107));
        jButton9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Reset");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        roundedpanel5.setRoundBottomLeft(15);
        roundedpanel5.setRoundBottomright(15);
        roundedpanel5.setRoundTopLeft(15);
        roundedpanel5.setRoundTopRight(15);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID Anggota");

        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Nama Anggota");

        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Jenis Pinjaman");

        jComboBox2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pinjaman Pokok", "Pinjaman Wajib", "Pinjaman Sukarela" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Tanggal");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("-");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("-");

        jButton3.setBackground(new java.awt.Color(0, 121, 107));
        jButton3.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tambah");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Jumlah Pinjaman");

        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("No. Rekening");

        jTextField15.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Bulan");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Tahun");

        javax.swing.GroupLayout roundedpanel5Layout = new javax.swing.GroupLayout(roundedpanel5);
        roundedpanel5.setLayout(roundedpanel5Layout);
        roundedpanel5Layout.setHorizontalGroup(
            roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel5Layout.createSequentialGroup()
                .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedpanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedpanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundedpanel5Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundedpanel5Layout.createSequentialGroup()
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(roundedpanel5Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton3)))))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(roundedpanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13)
                    .addGroup(roundedpanel5Layout.createSequentialGroup()
                        .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8)
                            .addComponent(jTextField15)
                            .addComponent(jTextField9)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        roundedpanel5Layout.setVerticalGroup(
            roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedpanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedpanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Berdasarkan ID:");

        jLabel22.setBackground(new java.awt.Color(0, 149, 117));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PINJAMAN");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/simpin/assets/1-removebg-preview (1).png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton4.setText("Ganti Bahasa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton5.setText("Log Aktivitas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jButton10.setText("Download laporan");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCover1Layout = new javax.swing.GroupLayout(panelCover1);
        panelCover1.setLayout(panelCover1Layout);
        panelCover1Layout.setHorizontalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCover1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(695, 695, 695)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCover1Layout.createSequentialGroup()
                                .addComponent(roundedpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panelCover1Layout.createSequentialGroup()
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelCover1Layout.setVerticalGroup(
            panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCover1Layout.createSequentialGroup()
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCover1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCover1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCover1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(roundedpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panelCover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCover1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCover1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
          
 public void loadMemberData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    // Create a left-alignment renderer
    DefaultTableCellRenderer leftAlignRenderer = new DefaultTableCellRenderer();
    leftAlignRenderer.setHorizontalAlignment(SwingConstants.LEFT);
    
    // Apply left alignment to all columns
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        jTable1.getColumnModel().getColumn(i).setCellRenderer(leftAlignRenderer);
    }

    // Reset the table data to avoid duplicate entries
    model.setRowCount(0);

    // Load data from database
    TodoRepo repo = new TodoRepo();
    repo.loadpinjaman(model);  // Assuming this method loads all members from DB into the table
}
    
    
    
    
    
    
    
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String idAnggotaInput = jTextField14.getText().trim();

// Cek apakah input kosong
if (idAnggotaInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan ID anggota yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Dapatkan model asli dari JTable
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// Buat TableRowSorter untuk menyaring data di JTable
TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
jTable1.setRowSorter(sorter);

// Filter berdasarkan ID Anggota (kolom pertama, indeks ke-0)
RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter("^" + idAnggotaInput + "$", 0); // 0 adalah indeks kolom pertama
sorter.setRowFilter(rf);

// Cek apakah ada hasil yang ditampilkan setelah filter
if (sorter.getViewRowCount() == 0) {
    JOptionPane.showMessageDialog(this, "ID anggota tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
    // Reset filter agar menampilkan semua data kembali
    sorter.setRowFilter(null);
}

    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    // Ambil input dari JTextField dan hapus spasi di depan/belakang
String idAnggotaInput = jTextField14.getText().trim();

if (idAnggotaInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan ID anggota yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Pastikan ID Anggota ada di database
TodoRepo repo = new TodoRepo();
int checkResult = repo.hapuspinjaman(idAnggotaInput);  // Panggil fungsi hapus untuk cek keberadaan ID

if (checkResult == 1) {
    // Jika data ditemukan dan berhasil dihapus di database, hapus di JTable
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    boolean found = false;

    // Cari ID anggota di kolom pertama (indeks kolom ke-0)
    for (int i = 0; i < model.getRowCount(); i++) {
        // Pastikan data diambil secara aman dan tidak null
        String tableId = model.getValueAt(i, 0) != null ? model.getValueAt(i, 0).toString().trim() : "";
        if (tableId.equals(idAnggotaInput)) {
            model.removeRow(i);  // Hapus baris dari tabel
            found = true;
            break;
        }
    }

    if (found) {
        JOptionPane.showMessageDialog(this, "Data Pinjaman telah dihapus.", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Data Pinjaman tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(this, "ID Pinjaman anggota tidak ditemukan di database.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
     String idInput = jTextField14.getText().trim(); // Ambil input dari JTextField8

// Cek apakah input kosong
if (idInput.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Masukkan ID yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    return;
}

// Dapatkan model asli dari JTable
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// Buat TableRowSorter untuk menyaring data di JTable
TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
jTable1.setRowSorter(sorter);

// Filter berdasarkan ID (kolom pertama, indeks 0)
RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter("^" + idInput + "$", 0); // Indeks 0 untuk kolom pertama (ID)
sorter.setRowFilter(rf);

// Cek apakah ada hasil yang ditampilkan setelah filter
if (sorter.getViewRowCount() == 0) {
    JOptionPane.showMessageDialog(this, "ID tidak ditemukan di tabel.", "Info", JOptionPane.INFORMATION_MESSAGE);
    // Reset filter agar menampilkan semua data kembali
    sorter.setRowFilter(null);
    return;
}

// Jika ditemukan, ambil indeks baris yang sesuai dengan filter
int modelRowIndex = sorter.convertRowIndexToModel(0); // Ambil baris pertama yang cocok

// Ambil data dari baris yang cocok
String nama = model.getValueAt(modelRowIndex, 1).toString(); // Kolom Nama
String jenisPinjaman = model.getValueAt(modelRowIndex, 2).toString(); // Kolom Jenis Pinjaman
String jumlah = model.getValueAt(modelRowIndex, 3).toString(); // Kolom Jumlah
String noRek = model.getValueAt(modelRowIndex, 4).toString(); // Kolom No Rek
String tanggal = model.getValueAt(modelRowIndex, 5).toString(); // Kolom Tanggal
String bulan = model.getValueAt(modelRowIndex, 6).toString(); // Kolom Bulan
String tahun = model.getValueAt(modelRowIndex, 7).toString(); // Kolom Tahun

// Tampilkan dialog untuk mengedit data
String newNama = JOptionPane.showInputDialog(this, "Edit Nama:", nama);

// Gunakan JComboBox untuk pilihan jenis pinjaman
JComboBox<String> pinjamanComboBox = new JComboBox<>(new String[]{"Pinjaman Pokok", "Pinjaman Wajib", "Pinjaman Sukarela"});
pinjamanComboBox.setSelectedItem(jenisPinjaman);

int pinjamanOption = JOptionPane.showConfirmDialog(
    this,
    pinjamanComboBox,
    "Edit Jenis Pinjaman:",
    JOptionPane.OK_CANCEL_OPTION,
    JOptionPane.PLAIN_MESSAGE
);
String newJenisPinjaman = (pinjamanOption == JOptionPane.OK_OPTION) ? (String) pinjamanComboBox.getSelectedItem() : null;

String newJumlah = JOptionPane.showInputDialog(this, "Edit Jumlah:", jumlah);
String newNoRek = JOptionPane.showInputDialog(this, "Edit No Rekening:", noRek);
String newTanggal = JOptionPane.showInputDialog(this, "Edit Tanggal:", tanggal);
String newBulan = JOptionPane.showInputDialog(this, "Edit Bulan:", bulan);
String newTahun = JOptionPane.showInputDialog(this, "Edit Tahun (4 digit):", tahun);

// Validasi tahun harus 4 digit
if (newTahun != null && !newTahun.matches("\\d{4}")) {
    JOptionPane.showMessageDialog(this, "Tahun harus terdiri dari 4 digit.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    newTahun = null;
}

// Update data di JTable jika input tidak dibatalkan
if (newNama != null && newJenisPinjaman != null && newJumlah != null && newNoRek != null && newTanggal != null && newBulan != null && newTahun != null) {
    model.setValueAt(newNama, modelRowIndex, 1);          
    model.setValueAt(newJenisPinjaman, modelRowIndex, 2);  
    model.setValueAt(newJumlah, modelRowIndex, 3);        
    model.setValueAt(newNoRek, modelRowIndex, 4);         
    model.setValueAt(newTanggal, modelRowIndex, 5);       
    model.setValueAt(newBulan, modelRowIndex, 6);         
    model.setValueAt(newTahun, modelRowIndex, 7);          

    JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Info", JOptionPane.INFORMATION_MESSAGE);
} else {
    JOptionPane.showMessageDialog(this, "Edit dibatalkan atau input tidak valid.", "Peringatan", JOptionPane.WARNING_MESSAGE);
}

// Reset filter untuk menampilkan semua data kembali
sorter.setRowFilter(null);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          if (jTable1.getRowSorter() != null) {
            // Reset filter agar semua data tampil kembali
            ((TableRowSorter<?>) jTable1.getRowSorter()).setRowFilter(null);
        } else {
            // Jika tidak menggunakan TableRowSorter, bisa langsung refresh model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.fireTableDataChanged(); // Memastikan data tabel diperbarui
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try {
    // Ambil nilai dari field input
    int idAnggota = Integer.parseInt(jTextField8.getText().trim());  // ID Anggota
    String namaAnggota = jTextField9.getText().trim();               // Nama Anggota
    String jenisPinjaman = jComboBox2.getSelectedItem().toString();  // Jenis Simpanan
    int jumlah = Integer.parseInt(jTextField13.getText().trim());    // Jumlah Pinjaman
    int no_rek = Integer.parseInt(jTextField15.getText().trim());    // No Rekening
    int tanggal = Integer.parseInt(jTextField11.getText().trim());   // Tanggal
    int bulan = Integer.parseInt(jTextField10.getText().trim());     // Bulan
    int tahun = Integer.parseInt(jTextField12.getText().trim());     // Tahun

    // Validasi bulan antara 1 dan 12
    if (bulan < 1 || bulan > 12) {
        JOptionPane.showMessageDialog(this, "Bulan harus antara 1 dan 12!", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tentukan jumlah hari maksimum dalam bulan tersebut
    int maxHari;
    switch (bulan) {
        case 1: case 3: case 5: case 7: case 8: case 10: case 12:
            maxHari = 31;
            break;
        case 4: case 6: case 9: case 11:
            maxHari = 30;
            break;
        case 2:
            // Periksa apakah tahun adalah kabisat
            if ((tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0)) {
                maxHari = 29;  // Februari tahun kabisat
            } else {
                maxHari = 28;  // Februari tahun biasa
            }
            break;
        default:
            maxHari = 0;  // Tidak mungkin terjadi, tapi kita perlu mendefinisikan
    }

    // Validasi tanggal apakah valid dalam bulan tersebut
    if (tanggal < 1 || tanggal > maxHari) {
        JOptionPane.showMessageDialog(this, 
            "Tanggal tidak valid untuk bulan " + bulan + " di tahun " + tahun + 
            ". Maksimum adalah " + maxHari + " hari.", 
            "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validasi apakah semua input sudah diisi
    if (jenisPinjaman.equalsIgnoreCase("Pilih")) {
        JOptionPane.showMessageDialog(this, "Jenis Pinjaman belum dipilih", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (namaAnggota.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama Anggota harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Gunakan DBUtil untuk menambahkan data ke database
    String query = "INSERT INTO pinjaman (idAnggota, namaAnggota, jenisPinjaman, jumlah, no_rek, tanggal, bulan, tahun) "
                 + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    try (Connection conn = (Connection) DBUtil.getConnection(); 
         PreparedStatement stmt = conn.prepareStatement(query)) {

        // Set parameter untuk query
        stmt.setInt(1, idAnggota);
        stmt.setString(2, namaAnggota);
        stmt.setString(3, jenisPinjaman);
        stmt.setInt(4, jumlah);
        stmt.setInt(5, no_rek);
        stmt.setInt(6, tanggal);
        stmt.setInt(7, bulan);
        stmt.setInt(8, tahun);

        // Eksekusi query
        int insertResult = stmt.executeUpdate();

        // Cek apakah data berhasil ditambahkan
        if (insertResult <= 0) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data ke database!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data ke database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tambahkan data baru ke tabel
    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
    tableModel.addRow(new Object[]{idAnggota, namaAnggota, jenisPinjaman, jumlah, no_rek, tanggal, bulan, tahun});

    // Reset field input setelah berhasil menambahkan data
    jTextField8.setText("");  // Reset ID Anggota
    jTextField9.setText("");  // Reset Nama Anggota
    jTextField13.setText(""); // Reset Jumlah
    jTextField15.setText(""); // Reset No Rekening
    jTextField11.setText(""); // Reset Tanggal
    jTextField10.setText(""); // Reset Bulan
    jTextField12.setText(""); // Reset Tahun
    jComboBox2.setSelectedIndex(0); // Reset pilihan jenis pinjaman

    // Tampilkan pesan sukses
    JOptionPane.showMessageDialog(this, "Data pinjaman berhasil ditambah", "Berhasil", JOptionPane.INFORMATION_MESSAGE);

} catch (NumberFormatException e) {
    // Tangani kesalahan jika input angka tidak valid
    JOptionPane.showMessageDialog(this, "ID Anggota, Jumlah, Tanggal, Bulan, dan Tahun harus berupa angka!", "Kesalahan Input", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
    Dashboard dashboard = new Dashboard();
    dashboard.setVisible(true);  // Langsung tampilkan JFrame Dashboard
    this.dispose();              // Menutup JFrame saat ini
} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error membuka Dashboard: " + e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if (isEnglish) {
        // Set text labels for Indonesian
        jLabel9.setText("ID Anggota");
        jLabel14.setText("Nama Anggota");
        jLabel14.setText("Jenis Kelamin");
        jLabel15.setText("Jenis Pinjaman");
       jLabel19.setText("Jumlah Pinjaman");
        jLabel23.setText("No. Rekening");
        jLabel16.setText("Tanggal");
        jLabel21.setText("Bulan");
        jLabel25.setText("Tahun");
       jButton3.setText("Tambah");
        jButton1.setText("Kembali");
        jButton4.setText("Ganti bahasa");
         jButton3.setText("Daftar");
         jLabel20.setText("Berdasarkan ID:");
         jButton6.setText("Cari");
         jButton7.setText("Hapus");
         jButton8.setText("Edit");
         jButton9.setText("Reset");
         
         
        // Set table column headers for Indonesian
        jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Nama");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Jenis Simpanan");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Jumlah");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("No Rek");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Tanggal");
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Bulan");
        jTable1.getColumnModel().getColumn(7).setHeaderValue("Tahun");

    } else {
        // Set text labels for English
         jLabel9.setText("Member ID");
         jLabel14.setText("Member name");
        jLabel14.setText("Gender");
        jLabel15.setText("Type Deposit");
        jLabel19.setText("Loan Amount");
        jLabel23.setText("Account number");
         jLabel16.setText("Date");
         jLabel21.setText("Month");
         jLabel25.setText("Year");
        jButton3.setText("Plus");
        jButton1.setText("Back");
        jButton4.setText("Change language");
         jButton3.setText("Address");
         jLabel20.setText("Based on NIK");
         jButton6.setText("Search");
         jButton7.setText("Delete");
         jButton8.setText("Ubah");
         jButton9.setText("Reset");

        // Set table column headers for English
           jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
        jTable1.getColumnModel().getColumn(1).setHeaderValue("Name");
        jTable1.getColumnModel().getColumn(2).setHeaderValue("Deposit type");
        jTable1.getColumnModel().getColumn(3).setHeaderValue("Results");
        jTable1.getColumnModel().getColumn(4).setHeaderValue("Account number");
        jTable1.getColumnModel().getColumn(5).setHeaderValue("Date");
        jTable1.getColumnModel().getColumn(6).setHeaderValue("Month");
        jTable1.getColumnModel().getColumn(7).setHeaderValue("Year");
    }

    // Refresh the table header after changing the language
    jTable1.getTableHeader().repaint();

    // Toggle the language flag for next usage
    isEnglish = !isEnglish;

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String sql = """
            SELECT namaAnggota, 
                   SUM(jumlah) AS totalPinjaman
            FROM pinjaman
            GROUP BY idAnggota, namaAnggota
            ORDER BY namaAnggota ASC
        """;

try (Connection connection = (Connection) DBUtil.getConnection();
     PreparedStatement stmt = connection.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery()) {

    StringBuilder messageBuilder = new StringBuilder("Daftar Pinjaman Anggota:\n\n");
    double totalKeseluruhan = 0;  // Variabel untuk menghitung total pinjaman keseluruhan

    // Mengolah hasil query
    while (rs.next()) {
        String nama = rs.getString("namaAnggota");  // Mengambil nama anggota
        double totalPinjaman = rs.getDouble("totalPinjaman");  // Mengambil total pinjaman anggota

        // Menggunakan waktu saat ini sebagai waktu peminjaman
        LocalDateTime waktuPeminjaman = LocalDateTime.now();
        LocalDate tanggalPeminjaman = waktuPeminjaman.toLocalDate();

        // Format waktu peminjaman ke HH:mm:ss
        String waktuFormatted = waktuPeminjaman.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        // Mengambil nama hari dalam bahasa Indonesia berdasarkan waktu saat ini
        String namaHari = tanggalPeminjaman.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("id", "ID"));

        // Menambahkan informasi pinjaman ke dalam message
        messageBuilder.append("Nama: ").append(nama).append("\n")
                      .append("Total Pinjaman: Rp ").append(String.format("%.2f", totalPinjaman)).append("\n")
                      .append("Waktu Peminjaman: ").append(tanggalPeminjaman.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")))
                      .append(" ").append(waktuFormatted)
                      .append(" (").append(namaHari).append(")\n\n");

        // Menambahkan total pinjaman ke total keseluruhan
        totalKeseluruhan += totalPinjaman;
    }

    // Jika tidak ada pinjaman yang terdaftar
    if (messageBuilder.toString().equals("Daftar Pinjaman Anggota:\n\n")) {
        JOptionPane.showMessageDialog(null, "Tidak ada pinjaman yang terdaftar.", "Info", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Menambahkan informasi total keseluruhan pinjaman
        messageBuilder.append("Jumlah Total Semua Pinjaman: Rp ").append(String.format("%.2f", totalKeseluruhan)).append("\n");

        // Menampilkan pesan dalam bentuk card message
        JOptionPane.showMessageDialog(null, messageBuilder.toString(), "Informasi Pinjaman Anggota", JOptionPane.INFORMATION_MESSAGE);
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      String outputFile = "D:\\Data_Pinjaman.pdf";

// Query untuk mengambil data pinjaman
String sql = "SELECT * FROM pinjaman";

try (Connection connection = (Connection) DBUtil.getConnection();
     PreparedStatement stmt = connection.prepareStatement(sql);
     ResultSet rs = stmt.executeQuery()) {

    // Membuat dokumen PDF
    Document document = new Document();
    PdfWriter.getInstance(document, new FileOutputStream(outputFile));

    // Membuka dokumen untuk menulis
    document.open();

    // Menulis judul dokumen dengan bold
    Font boldFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
    document.add(new Paragraph("Daftar Pinjaman Anggota", boldFont));
    document.add(new Paragraph("========================================"));

    // Menulis data pinjaman
    while (rs.next()) {
        int idAnggota = rs.getInt("idAnggota");
        String namaAnggota = rs.getString("namaAnggota");
        String jenisPinjaman = rs.getString("jenisPinjaman");
        int jumlah = rs.getInt("jumlah");
        int noRek = rs.getInt("no_rek");
        int tanggal = rs.getInt("tanggal");
        int bulan = rs.getInt("bulan");
        int tahun = rs.getInt("tahun");
        int jam = rs.getInt("jam");
        int menit = rs.getInt("menit");
        int detik = rs.getInt("detik");

        // Format tanggal dan waktu
        String formattedDate = String.format("%02d-%02d-%d", tanggal, bulan, tahun);
        String formattedTime = String.format("%02d:%02d:%02d", jam, menit, detik);

        // Menambahkan data pinjaman ke dalam dokumen PDF
        document.add(new Paragraph("ID Anggota: " + idAnggota));
        document.add(new Paragraph("Nama Anggota: " + namaAnggota));
        document.add(new Paragraph("Nomor Rekening: " + noRek));
        document.add(new Paragraph("Jenis Pinjaman: " + jenisPinjaman));
        document.add(new Paragraph("Jumlah Pinjaman: " + jumlah));
        document.add(new Paragraph("Tanggal: " + formattedDate));
        document.add(new Paragraph("Waktu: " + formattedTime));
        document.add(new Paragraph("\n----------------------------------------\n"));
    }

    // Menutup dokumen PDF
    document.close();

    // Memberikan informasi kepada pengguna bahwa PDF telah dibuat
    JOptionPane.showMessageDialog(null, "Data pinjaman berhasil diekspor ke PDF: " + outputFile,
                                  "Berhasil", JOptionPane.INFORMATION_MESSAGE);

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
} catch (FileNotFoundException e) {
    JOptionPane.showMessageDialog(null, "File tidak ditemukan atau tidak dapat disimpan.", "Error", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
} catch (DocumentException ex) {
    JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat membuat file PDF.", "Error", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace();
}

    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private aplikasi.simpin.component.PanelCover panelCover1;
    private aplikasi.simpin.component.roundedpanel roundedpanel1;
    private aplikasi.simpin.component.roundedpanel roundedpanel2;
    private aplikasi.simpin.component.roundedpanel roundedpanel3;
    private aplikasi.simpin.component.roundedpanel roundedpanel4;
    private aplikasi.simpin.component.roundedpanel roundedpanel5;
    // End of variables declaration//GEN-END:variables
}
